"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Kev"
email = "kyfeman@gmail.com"

[ui]
editor = "micro +2"
diff-editor = ":builtin"
default-command = "status"
conflict-marker-style= "snapshot"
graph.style = "square"
log-word-wrap   = true
paginate  = "auto"
pager = ":builtin"

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'

