# Theming
font: VictorMono Nerd Font 16
background: "#24273A"
color: "#8AADF4"
border: "#8AADF4"
separator: " âžœ "
border_width: 1
corner_r: 5
padding: 5 # Defaults to corner_r
# rows_per_column: 5

# Anchor and margin
anchor: center # One of center, left, rght, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor s not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

menu:
  - key: "a"
    desc: ai
    submenu:
      - key: "a"
        desc: aichat
        # cmd: kitty aichat -m llama-cpp:lfm2-8b -r concise -s session --empty-session
        cmd: mmsg -d toggle_named_scratchpad,aichat,none,open_aichat
      - key: "k"
        desc: kill llama-server
        cmd: pkill llama-server
      - key: "1"
        desc: Gemma3-4b (vision)
        cmd: notify-send -u low 'AI Model' 'Loading Gemma3-4b' && pkill llama-server; llama-server -a 'Gemma3-4b (vision)' -m ~/Code/models/ggml-org_gemma-3-4b-it-GGUF_gemma-3-4b-it-Q4_K_M.gguf --mmproj ~/Code/models/ggml-org_gemma-3-4b-it-GGUF_mmproj-model-f16.gguf --temp 1.0 --top-k 64 --min-p 0.00 --top-p 0.95 --repeat-penalty 1.0 --ctx-size 8192 --port 8081 --host 127.0.0.1
      - key: "2"
        desc: LFM2-8B-A1B (fast and concise)
        cmd: notify-send -u low 'AI Model' 'Loading LFM2' && pkill llama-server; llama-server -a 'LFM2-8B-A1B' -m ~/Code/models/LFM2-8B-A1B-Q4_K_M.gguf --ctx-size 8192 --temp 0.3 --min-p 0.15 --repeat-penalty 1.05 --port 8081 --host 127.0.0.1
      - key: "3"
        desc: Qwen3-4B-Instruct (fast and friendly)
        cmd: notify-send -u low 'AI Model' 'Loading Qwen3-4B-Instruct' && pkill llama-server; niri msg action spawn-sh -- "llama-server -a 'Qwen3-4B-Instruct' -m ~/Code/models/Qwen3-4B-Instruct-2507-IQ4_XS.gguf --ctx-size 8192 --temp 0.7 --top-p 0.8 --top-k 20 --min-p 0 --presence-penalty 1.05 --port 8081 --host 127.0.0.1
      - key: "4"
        desc: Qwen3-30B-A3B (MoE)
        cmd: notify-send -u low 'AI Model' 'Loading Qwen3-30B-A3B' && pkill llama-server; niri msg action spawn-sh -- "llama-server -a 'Qwen-30b-A3B' -m ~/Code/models/Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf --ctx-size 8192 --temp 0.7 --top-p 0.8 --min-p 0 --top-k 20 --presence-penalty 1.05 --port 8081 --host 127.0.0.1
      - key: "5"
        desc: GPT-OSS-20b (MoE/thinking)
        cmd: notify-send -u low 'AI Model' 'Loading GPT-OSS-20B' && pkill llama-server; niri msg action spawn-sh -- "llama-server -a 'GPT-OSS-20b' -m ~/Code/models/gpt-oss-20b-MXFP4.gguf --jinja --ctx-size 8192 -ub 2048 -b 2048 --n-cpu-moe 21 --temp 1.0 --top-p 1.0 --top-k 0 --min-p 0 --port 8081 --host 127.0.0.1
      - key: "6"
        desc: Enoch-12b
        cmd: notify-send -u low 'AI Model' 'Loading Enoch-12b' && pkill llama-server; niri msg action spawn-sh -- "llama-server -m ~/Code/models/Enoch-CWC-Mistral-Nemo-12B-v2-GGUF-q4_k_m.gguf -a 'Enoch-12b' --ctx-size 8192 --port 8081 --host 127.0.0.1
  - key: "c"
    desc: configs
    submenu:
      - key: "f"
        desc: fish
        submenu:
          - key: "a"
            desc: aliases/abbrs
            cmd: kitty nvim ~/NixOS/home/dots/fish/conf.d/aliases-abbrs.fish
          - key: "c"
            desc: config
            cmd: kitty nvim ~/NixOS/home/dots/fish/config.fish
          - key: "f"
            desc: functions
            cmd: kitty yazi ~/NixOS/home/dots/fish/functions
      - key: "h"
        desc: helix
        submenu:
          - key: "c"
            desc: config
            cmd: kitty nvim ~/.config/helix/config.toml
          - key: "l"
            desc: languages
            cmd: kitty nvim ~/.config/helix/languages.toml
          - key: "e"
            desc: expansions
            cmd: kitty yazi ~/.config/helix/snippets
      - key: "n"
        desc: nixos
        submenu:
          - key: "u"
            desc: users
            cmd: kitty nvim ~/NixOS/modules/users.nix
          - key: "e"
            desc: environment
            cmd: kitty nvim ~/NixOS/modules/environment.nix
          - key: "p"
            desc: programs
            cmd: kitty nvim ~/NixOS/modules/programs.nix
          - key: "s"
            desc: services
            cmd: kitty nvim ~/NixOS/modules/services.nix
          - key: "f"
            desc: flake
            cmd: kitty nvim ~/NixOS/flake.nix
          - key: "h"
            desc: home
            cmd: kitty nvim ~/NixOS/home/home.nix
      - key: "c"
        desc: which-key menus
        cmd: kitty nvim ~/.config/wlr-which-key/mango-config.yaml
      - key: "m"
        desc: mango
        submenu:
          - key: "b"
            desc: binds
            cmd: kitty nvim ~/.config/mango/binds.conf
          - key: "c"
            desc: config
            cmd: kitty nvim ~/.config/mango/config.conf
          - key: "r"
            desc: rules
            cmd: kitty nvim ~/.config/mango/rules.conf
          - key: "l"
            desc: layout config (scroll)
            cmd: kitty nvim ~/.config/mango/layouts/scroll.conf
      - key: "N"
        desc: niri
        submenu:
          - key: "b"
            desc: binds
            cmd: kitty nvim ~/.config/niri/binds.kdl
          - key: "c"
            desc: config.kdl
            cmd: kitty nvim ~/.config/niri/config.kdl
          - key: "e"
            desc: environment
            cmd: kitty nvim ~/.config/niri/environment.kdl
          - key: "i"
            desc: input
            cmd: kitty nvim ~/.config/niri/input.kdl
          - key: "l"
            desc: layer-rules
            cmd: kitty nvim ~/.config/niri/layer-rules.kdl
          - key: "L"
            desc: layout
            cmd: kitty nvim ~/.config/niri/layout.kdl
          - key: "o"
            desc: output
            cmd: kitty nvim ~/.config/niri/output.kdl
          - key: "s"
            desc: spawns
            cmd: kitty nvim ~/.config/niri/spawns.kdl
          - key: "w"
            desc: window-rules
            cmd: kitty nvim ~/.config/niri/window-rules.kdl
      - key: "p"
        desc: color picker
        submenu:
          - key: "p"
            desc: picker with color mixer
            cmd: wl-color-picker
          - key: "z"
            desc: picker with zoom
            cmd: hyprpicker -f hex -a
  - key: "d"
    desc: dms
    submenu:
      - key: "k"
        desc: kill shell
        cmd: dms kill
      - key: "l"
        desc: launch shell
        cmd: dms run
      - key: "r"
        desc: restart shell
        cmd: dms restart
      - key: "s"
        desc: open settings
        cmd: dms ipc settings toggle
      - key: "w"
        desc: wallpaper
        submenu:
          - key: "n"
            desc: next wallpaper
            cmd: dms ipc wallpaper next
          - key: "p"
            desc: previous wallpaper
            cmd: dms ipc wallaper prev
  - key: "f"
    desc: file manager
    cmd: nautilus
  - key: "l"
    desc: launch
    submenu:
      - key: "b"
        desc: btop
        cmd: kitty btop
      - key: "c"
        desc: calendar
        cmd: kitty khal interactive
      - key: "e"
        desc: editor
        cmd: kitty nvim
      - key: "f"
        desc: firefox
        cmd: firefox
      - key: "m"
        desc: magnifier
        cmd: hyprmagnifier -t --size 800x800
      - key: "s"
        desc: spotify
        cmd: spotify --no-zygote
      - key: "y"
        desc: yazi
        submenu:
          - key: b
            desc: bin
            cmd: kitty yazi ~/.local/bin
          - key: c
            desc: config
            cmd: kitty yazi ~/.config
          - key: C
            desc: code
            cmd: kitty yazi ~/Code
          - key: d
            desc: downloads
            cmd: kitty yazi ~/Downloads
          - key: h
            desc: home
            cmd: kitty yazi
          - key: m
            desc: meditation tracks
            cmd: kitty yazi ~/Music/meditational/best
          - key: n
            desc: nixos
            cmd: kitty yazi ~/NixOS
  - key: "m"
    desc: music
    submenu:
      - key: "m"
        desc: mpd
        cmd: kitty rmpc
      - key: "s"
        desc: spotify
        cmd: kitty spotify_player
      - key: "v"
        desc: visualizer
        cmd: kitty cava
      - key: "a"
        desc: alsamixer
        cmd: kitty alsamixer
      - key: "p"
        desc: pipewire mixer
        submenu:
          - key: "g"
            desc: gui
            cmd: pwvucontrol
          - key: "t"
            desc: tui
            cmd: kitty ncpamixer
  - key: "n"
    desc: network
    cmd: kitty --app-id=nmtui nmtui
  - key: "p"
    desc: podman
    submenu:
      - key: "r"
        desc: restart container
        submenu:
          - key: "m"
            desc: miniflux
            cmd: kitty podman compose restart miniflux
          - key: "o"
            desc: open-webui
            cmd: kitty podman compose restart open-webui
          - key: "s"
            desc: silverbullet
            cmd: kitty podman compose restart silverbullet
      - key: "u"
        desc: update container
        submenu:
          - key: "m"
            desc: miniflux
            cmd: kitty /home/kev/Code/podman/miniflux/miniflux-update-restart
          - key: "o"
            desc: openweb-ui
            cmd: kitty /home/kev/Code/podman/openweb-ui/openwebui-update-restart
          - key: "s"
            desc: silverbullet
            cmd: kitty /home/kev/Code/podman/silverbullet/silverbullet-update-restart
      - key: "p"
        desc: podman-tui
        cmd: kitty podman-tui

  - key: "r"
    desc: repos
    submenu:
      - key: "1"
        desc: nixos
        cmd: kitty  --app-id repo --title=nixos -e jjui ~/NixOS
      - key: "2"
        desc: dms
        cmd: kitty  --app-id repo --title=dms -e jjui ~/.config/quickshell/dms
      - key: "3"
        desc: mangowc
        cmd: kitty  --app-id repo --title=dms -e jjui ~/Code/mangowc
      - key: "4"
        desc: niri
        cmd: kitty  --app-id repo --title=niri -e jjui ~/Code/niri
      - key: "5"
        desc: helix
        cmd: kitty  --app-id repo --title=helix -e jjui ~/Code/helix
      - key: "6"
        desc: jjui
        cmd: kitty  --app-id repo --title=jjui -e jjui ~/Code/jjui
      - key: "7"
        desc: dgop
        cmd: kitty  --app-id repo --title=dgop -e jjui ~/Code/dgop
      - key: "8"
        desc: dms-plugins
        cmd: kitty  --app-id repo --title=dms-plugins -e jjui ~/Code/dms-plugins
  - key: "s"
    desc: toggle system theme
    cmd: toggle-system-theme
