[metadata]
name = "nix-profile"
description = "List packages installed in user profile"
requirements = ["nix"]

[source]
command = "nix profile list --json > /tmp/nix-profile.json && jq -r '.elements | keys[]' /tmp/nix-profile.json"
# output = "{trim}"
# ansi = true

[preview]
command = "jq -r '.elements.\"{}\" | {originalUrl, storePaths}' /tmp/nix-profile.json"
# ansi = true
